spring:
  application:
    name: library-server
  jpa:
   show_sql: true
   database: POSTGRESQL
   hibernate:
    ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
logging:
  file: log.txt
  level: error
